### ISSUE TITLE
Add watchdog

### ISSUE THREAD

**Issue by Se3ker** [ghi-electronics/TinyCLR-Ports#467] opened 2018-10-02 19:04 UTC
Please verify this works, and add to main

```
public class Watchdog
    {
        // Page 415 - Independent watchdog (IWDG)
        // RM0368 Reference manual - STM32F401xB/C and STM32F401xD/E advanced ARM®-based 32-bit MCUs
        // https://www.st.com/resource/en/reference_manual/dm00096844.pdf
        // http://kodfilemon.blogspot.com/2017/07/watchdog-iwdg-w-tinyclr-os.html

        public static bool LastReboot
        {
            get
            {
                var rccAddr = new IntPtr(0x40023800);
                int rccCsrValue = Marshal.ReadInt32(rccAddr, 0x74);
                return IsIwdgRstf(rccCsrValue);
            }
        }

        public static void Start(TimeSpan period)
        {
            ResetLastReboot();
            SetTimings(period);
            WriteIwdgKr(0xCCCC);
        }

        public static void Reset()
        {
            WriteIwdgKr(0xAAAA);
        }

        private static void ResetLastReboot()
        {
            var rccAddr = new IntPtr(0x40023800);
            int rccCsrValue = Marshal.ReadInt32(rccAddr, 0x74);

            if (IsIwdgRstf(rccCsrValue))
            {
                const int rmvfMask = 0x01000000;
                rccCsrValue = rccCsrValue | rmvfMask;
                Marshal.WriteInt32(rccAddr, 0x74, rccCsrValue);
            }
        }

        private static void WriteIwdgKr(int value)
        {
            Marshal.WriteInt32(new IntPtr(0x40003000), value);
        }

        private static bool IsIwdgRstf(int rccCsrValue)
        {
            const int iwdgRstfMask = 0x20000000;
            return (rccCsrValue & iwdgRstfMask) > 0;
        }

        private static void SetTimings(TimeSpan period)
        {
            const int kHzLsi = 32000;

            long usPeriod = ((period.Ticks * 1000) / TimeSpan.TicksPerMillisecond);
            int[] dividers = { 4, 8, 16, 32, 64, 128, 256 };
            for (int i = 0; i < dividers.Length; i++)
            {
                int usMin = (dividers[i] * 1000 * 1000) / kHzLsi;
                if (usPeriod >= usMin)
                {
                    int counter = (int)(usPeriod / usMin - 1);
                    if (counter < 0 | counter > 0xFFF)
                        continue;

                    SetIwdgPrAndRlr(i, counter);
                    return;
                }
            }

            throw new InvalidOperationException("Invalid period (0.125..32768 ms).");
        }

        private static void SetIwdgPrAndRlr(int prValue, int rlrValue)
        {
            var iwdgKrAddr = new IntPtr(0x40003000);
            Marshal.WriteInt32(iwdgKrAddr, 0x5555);
            Marshal.WriteInt32(iwdgKrAddr, 0x04, prValue);
            Marshal.WriteInt32(iwdgKrAddr, 0x08, rlrValue);
        }
    }
```

**Comment by Arke64** [comment] 2018-10-03 15:53
Thanks for the work here, we're tracking watchdog in a different issue, so we'll close this one as a duplicate.

Duplicate of ghi-electronics/TinyCLR-Libraries#157

**Closed by Arke64** 2018-10-03 15:53 UTC
