### ISSUE TITLE
GpioPin.Read().ToString()

### ISSUE THREAD

**Issue by Se3ker** [ghi-electronics/TinyCLR-Ports#631] opened 2019-06-15 12:56 UTC
Please implement .ToString() of GpioPin.Read()

**Comment by Arke64** [comment] 2019-06-18 19:05
What do you expect it to return? https://docs.microsoft.com/en-us/uwp/api/windows.devices.gpio.gpiopin doesn't document ToString being overriden.

**Comment by Se3ker** [comment] 2019-06-19 09:53
Debug.WriteLine(GpioPin.Read().ToString());
Either "High/Low" or "1/0" if it has a .ToString() it should implement it.

Its better then:
if (GpioPin.Read() == GpioPinValue.High) Debug.WriteLine("HIGH") else Debug.WriteLine("LOW")

**Comment by Arke64** [comment] 2019-06-19 15:38
Read() just returns a bool, we can't change how ToString() works on that, it'll return "True" or "False".

So `Debug.WriteLine(GpioPin.Read().ToString());` will show "True" or "False", which means "High" and "Low" respectively.

**Comment by Se3ker** [comment] 2019-06-19 19:55
Read() return a GpioPinValue not bool

**Comment by Arke64** [comment] 2019-06-19 20:48
Ah, right. Sorry.

In that case, `GpioPinValue` is an enum, we don't have control over what its `ToString` returns.

More generally in TinyCLR, enums return the underlying integer value in their `ToString`, not their name like on other platforms. While adding that is something on our todo list, it's not an easy fix because the metadata is not on the device. That feature is tracked by ghi-electronics/TinyCLR-Core#419, so we'll close this as a duplicate of that.

However, `GpioPinValue.Low` is 0 and `GpioPinValue.High` is 1, so with the above enum behavior, it's close to what you proposed.

**Closed as completed by Arke64** 2019-06-19 20:48 UTC
