### ISSUE TITLE
Could not deploy application sometime on small devices.

### ISSUE THREAD

**Issue by Palomino34** [ghi-electronics/TinyCLR-Ports#142] opened 2018-01-04 15:17 UTC
A message will be thrown:
"Internal error: call to memory allocation during garbage collection!!!"

Usually happens on devices have less memory like G30/USBizi/FEZCLR.

**Comment by Arke64** [comment] 2018-01-04 15:18
Duplicate of ghi-electronics/TinyCLR-Core#178

**Closed by Arke64** 2018-01-04 15:18 UTC
Labels: bug
